### ISSUE TITLE
[EPIC] Habitica Expansion

### ISSUE THREAD

**Issue by ghost** [Knights-Of-Academia/horace#169]
- [ ] #10 Guild command (report the current number of users in the Habitica guild)
- [ ] Dynamic !clan and !apply 
    - !clan should have usernames set in a DB rather than static 
    - !clan should show current member count
    - !apply should work like the website and not work if clan is full
- [ ] Tracking Challenge of the Week participation
    - how many times have you made vows?
    - how many times have you actually participated? (might require linking Habitica accounts to Horace via username being saved)
- [ ] Show someone's profile with !habitica @username
